### ISSUE TITLE
Each child in a list should have a unique "key" prop error is logged in the console

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-react#58] opened 2024-03-16 07:31 UTC
## Description  
`Each child in a list should have a unique "key" prop` error is logged in the console when add igniteui component to the view.

## Steps to reproduce  
I have this component:

```ts
import { IgrButton, IgrButtonModule } from 'igniteui-react';
IgrButtonModule.register();
export default function IgView() {
  return (
    <div>
      <IgrButton><span>Button</span></IgrButton>
    </div>
  );
}
```

## Result  
`Each child in a list should have a unique "key" prop` error is logged in the console.

## Expected result  
Adding igniteui component should not log any errors in the console.

**Comment by MayaKirova** [comment] 2024-04-03 08:15
@wnvko @ChronosSF Unfortunately this is by design for all react components that have children, more info and additional discussion around this can be found [here](https://infragistics.visualstudio.com/NetAdvantage/_workitems/edit/26058)

**Comment by MayaKirova** [comment] 2024-04-03 08:21
Closing since `key` is required by design in the current wrappers.

**Closed by MayaKirova** 2024-04-03 08:21 UTC
Labels: :bug: bug, wontfix
